### list of users
GET http://localhost:3000/users?limit=2
Accept: application/json

### list of single users
GET http://localhost:3000/users/1
Accept: application/json

### create users
POST http://localhost:3000/users
Content-Type: application/json

{
    "first_name": "John",
    "last_name": "Doe",
    "email": "test1@test.com",
    "about": "Making tutorial"
}

### Seeding database with faker data for test
POST http://localhost:3000/seed
Content-Type: application/json

{}

### UPDATE user by id
PUT http://localhost:3000/users/102
Content-Type: application/json

{
    "first_name": "John",
    "last_name": "Doe 2",
    "email": "test1@test.com",
    "about": "Making tutorial update good"
}